USE [PartnersNonmotorDB]
GO

SELECT [pol_yr]
      ,[pol_br]
      ,[pol_pre]
      ,[pol_no]
      ,[endos_seq]
      ,convert(datetime,substring([app_date],4,3)+ substring([app_date],1,3)+substring([app_date],7,5)+substring([app_date],12,10))[app_date]
      ,[ref_type]
      ,[ref_yr]
      ,[ref_no]
      ,[app_yr]
      ,[app_no]
      ,[coins_policy]
      ,[product_code]
      ,[period_term]
      ,convert(datetime,substring([start_date],4,3)+ substring([start_date],1,3)+substring([start_date],7,5)+substring([start_date],12,10))[start_date]
      ,convert(datetime,substring([end_date],4,3)+ substring([end_date],1,3)+substring([end_date],7,5)+substring([end_date],12,10))[end_date]
      ,convert(datetime,substring([issue_date],4,3)+ substring([issue_date],1,3)+substring([issue_date],7,5)+substring([issue_date],12,10))[issue_date]
      ,convert(datetime,substring([agreement_date],4,3)+ substring([agreement_date],1,3)+substring([agreement_date],7,5)+substring([agreement_date],12,10))[agreement_date]
      ,[attachment]
      ,[broker_code]
      ,[sale_flag]
      ,[sale_code]
      ,[license_no]
      ,[sumins_amt]
      ,[deduct_per]
      ,[deduct_amt]
      ,[net_premium]
      ,[stamp_per]
      ,[stamp]
      ,[vat]
      ,[tax_per]
      ,[tax]
      ,[total_premium]
      ,[add_net]
      ,[add_stamp]
      ,[add_vat]
      ,[add_tax]
      ,[add_total]
      ,[discnt_per]
      ,[discnt]
      ,[comm_per]
      ,[comm]
      ,[flag_calculate]
      ,[flag_language]
      ,[flag_print]
      ,[flag_insurance]
      ,[flag_group]
      ,[flag_factor]
      ,[flag_receipt]
      ,[flag_export]
      ,[renew_seq]
      ,[rec_status]
      ,[key_login]
      ,convert(datetime,substring([key_datetime],4,3)+ substring([key_datetime],1,3)+substring([key_datetime],7,5)+substring([key_datetime],12,10))[key_datetime]
      ,[update_login]
      ,convert(datetime,substring([update_datetime],4,3)+ substring([update_datetime],1,3)+substring([update_datetime],7,5)+substring([update_datetime],12,10))[update_datetime]
      ,[approve_login]
      ,convert(datetime,substring([approve_datetime],4,3)+ substring([approve_datetime],1,3)+substring([approve_datetime],7,5)+substring([approve_datetime],12,10))[approve_datetime]
      ,[check_login]
      ,convert(datetime,substring([check_datetime],4,3)+ substring([check_datetime],1,3)+substring([check_datetime],7,5)+substring([check_datetime],12,10))[check_datetime]
      ,[check_method]
      ,[print_login]
      ,convert(datetime,substring([print_datetime],4,3)+ substring([print_datetime],1,3)+substring([print_datetime],7,5)+substring([print_datetime],12,10))[print_datetime]
      ,[print_seq]
      ,[cancel_login]
      ,convert(datetime,substring([cancel_datetime],4,3)+ substring([cancel_datetime],1,3)+substring([cancel_datetime],7,5)+substring([end_date],12,10))[cancel_datetime]
      ,[notify_name]
      ,convert(datetime,substring([notify_datetime],4,3)+ substring([notify_datetime],1,3)+substring([notify_datetime],7,5)+substring([end_date],12,10))[notify_datetime]
      ,[cancel_amt]
      ,convert(datetime,substring([tr_datetime],4,3)+ substring([tr_datetime],1,3)+substring([tr_datetime],7,5)+substring([tr_datetime],12,10))[tr_datetime]
      ,[ins_type]
      ,[flag_paid]
      ,convert(datetime,substring([paid_date],4,3)+ substring([paid_date],1,3)+substring([paid_date],7,5)+substring([paid_date],12,10))[paid_date]
      ,[pol_group]
      ,[comm_extra_target_per]
      ,[target_premium]
      ,[comm_extra_target]
      ,[comm_fix_per]
      ,[comm_office_per]
      ,[comm_manager]
      ,[comm_due_per]
      ,[comm_computer_per]
      ,[comm_add_per]
      ,[comm_extra_target_prem_per]
      ,[comm_extra_target_policy_per]
      ,[comm_extra_loss_ratio_per]
      ,[comm_broker_bysale_per]
      ,[comm_broker_bycomp_per]
      ,[comm_vat_per]
      ,[total_comm_per]
      ,[vat_per]
      ,[target_prem]
      ,[target_policy]
      ,[credit_term]
      ,[credit_amt]
      ,[comm_fix]
      ,[comm_office]
      ,[comm_manager_per]
      ,[comm_due]
      ,[comm_computer]
      ,[comm_add]
      ,[comm_extra_target_prem]
      ,[comm_extra_target_policy]
      ,[comm_extra_loss_ratio]
      ,[comm_broker_bysale]
      ,[comm_broker_bycomp]
      ,[comm_vat]
      ,[total_comm]
      ,[comm_supervisor_per]
      ,[comm_supervisor]
      ,[comm_adjust_per]
      ,[comm_adjust]
      ,[adjust_login]
      ,convert(datetime,substring([adjust_datetime],4,3)+ substring([adjust_datetime],1,3)+substring([adjust_datetime],7,5)+substring([adjust_datetime],12,10))[adjust_datetime]
      ,[permit_login]
      ,convert(datetime,substring([permit_datetime],4,3)+ substring([permit_datetime],1,3)+substring([permit_datetime],7,5)+substring([permit_datetime],12,10))[permit_datetime]
      ,[brokerage_per]
      ,[flag_brokerage_by]
      ,[sale_ref_no]
      ,[comm_cal_vat]
      ,[comm_cal_vat_per]
      ,[comm_upper_per]
      ,[comm_upper]
      ,[comm_before_vat_per]
      ,[comm_before_vat]
      ,[comm_diff_per]
      ,[comm_diff]
      ,[comm_branch]
      ,[comm_branch_per]
      ,[comm_project]
      ,[comm_project_per]
      ,[acc_no]
      ,[bank_code]
      ,[war_bookno]
      ,[war_docno]
      ,[comm_service_per]
      ,[comm_service]
      ,[treaty_code]
      ,[flag_vat]
      ,[comm_adjust_vat_per]
      ,[comm_adjust_vat]
      ,[comm_adjust_cal_vat_per]
      ,[comm_adjust_cal_vat]
      ,[flag_send]
      ,[send_date]
      ,[channel_code]
      ,[pol_group_refno]
  FROM [dbo].[Temp_his_policy_stag]

GO


